#!/usr/bin/env python3
"""Mock-up: one verse slide in several colour variants -> out/slides_mock/<variant>.png (1920x1080).

    python3 slides/mock.py

XeLaTeX via Tectonic (~/.local/tectonic), fonts from the stotra-sangrahah repo:
Sanskrit 2003 for Devanāgarī, Gentium Basic for IAST. Page is 16in x 9in (120 px/in at 1080p);
rendered at 240 dpi and downscaled for clean anti-aliasing.
"""
import os, subprocess
from indic_transliteration import sanscript

import sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "pipeline"))
from config import FONTS, TECTONIC, FFMPEG                 # noqa: E402
OUT = "out/slides_mock"

TITLE_DEVA, TITLE_IAST = "गणेशभुजङ्गम्", "Gaṇeśa Bhujaṅgam"
NUM = 1
PADAS = ["रणत् क्षुद्रघण्टानिनादाभिरामं", "चलत् ताण्डवोद् दण्डवत्पद्मतालम्",
         "लसत् तुन्दिलाङ्गोपरिव्यालहारं", "गणाधीशमीशानसूनुं तमीडे"]

VARIANTS = {  # name: (centre, edge, text, accent)
    "maroon":    ("6B1A1F", "1C0607", "F3E9D2", "C9A55C"),
    "indigo":    ("243266", "080C22", "EFE4CC", "C9A55C"),
    "aubergine": ("4A1B4E", "12071A", "F3E9D2", "D4AF6A"),
}

DEVA_DIGITS = str.maketrans("0123456789", "०१२३४५६७८९")


def iast(s):
    return sanscript.transliterate(s, sanscript.DEVANAGARI, sanscript.IAST)


def tex(centre, edge, text, accent):
    n = str(NUM).translate(DEVA_DIGITS)
    deva = [PADAS[0], PADAS[1] + " ।", PADAS[2], PADAS[3] + f" ॥{n}॥"]
    roman = [iast(PADAS[0]), iast(PADAS[1]) + " |", iast(PADAS[2]), iast(PADAS[3]) + f" || {NUM} ||"]
    dl = r"\\[0.35em]".join(deva)
    rl = r"\\[0.15em]".join(roman)
    return rf"""
\documentclass{{article}}
\usepackage[paperwidth=16in,paperheight=9in,margin=0in]{{geometry}}
\usepackage{{fontspec,xcolor,tikz}}
\usetikzlibrary{{shadings}}
\pagestyle{{empty}}
\newfontfamily\deva[Path={FONTS},Script=Devanagari]{{sanskrit2003-5-spac-diaresis.ttf}}
\newfontfamily\iast[Path={FONTS},ItalicFont=GenBasI.ttf]{{GenBasR.ttf}}
\definecolor{{bgc}}{{HTML}}{{{centre}}}\definecolor{{bge}}{{HTML}}{{{edge}}}
\definecolor{{txt}}{{HTML}}{{{text}}}\definecolor{{acc}}{{HTML}}{{{accent}}}
\begin{{document}}
\begin{{tikzpicture}}[remember picture,overlay]
  % background: soft radial gradient, centre slightly above middle
  \shade[inner color=bgc,outer color=bge] ([xshift=-2in,yshift=-5in]current page.south west)
        rectangle ([xshift=2in,yshift=3in]current page.north east);
  % header: title + thin accent rules
  \node[anchor=north,yshift=-0.55in,text=acc] at (current page.north)
       {{\deva\fontsize{{26}}{{30}}\selectfont {TITLE_DEVA}}};
  \node[anchor=north,yshift=-1.12in,text=acc] at (current page.north)
       {{\iast\itshape\fontsize{{15}}{{18}}\selectfont {TITLE_IAST}}};
  \draw[acc,line width=0.6pt] ([xshift=-2.2in,yshift=-1.55in]current page.north) -- ++(4.4in,0);
  \fill[acc] ([yshift=-1.55in]current page.north) circle (2.2pt);
  % verse: Devanāgarī
  \node[anchor=center,yshift=0.55in,text=txt,align=center,
        font=\deva\fontsize{{42}}{{56}}\selectfont] at (current page.center) {{{dl}}};
  % IAST
  \node[anchor=north,yshift=-1.55in,text=txt,align=center,opacity=0.82,
        font=\iast\itshape\fontsize{{21}}{{27}}\selectfont] at (current page.center) {{{rl}}};
  % footer
  \draw[acc,line width=0.4pt,opacity=0.5] ([xshift=0.8in,yshift=0.62in]current page.south west)
        -- ([xshift=-0.8in,yshift=0.62in]current page.south east);
  \node[anchor=south west,xshift=0.8in,yshift=0.3in,text=txt,opacity=0.62] at (current page.south west)
       {{\iast\fontsize{{11}}{{13}}\selectfont stotrasamhita.github.io \ \textbullet\ \ github.com/stotrasamhita/stotra-sangrahah}};
  \node[anchor=south east,xshift=-0.8in,yshift=0.3in,text=txt,opacity=0.62] at (current page.south east)
       {{\iast\fontsize{{11}}{{13}}\selectfont Chant generated by AI with Vāgdhenu \ \textbullet\ \ github.com/prathoshap/vagdhenu}};
\end{{tikzpicture}}
\end{{document}}
"""


TITLE_META = [(None, "आदिशङ्कराचार्यः"), ("छन्दः", "भुजङ्गप्रयातम्")]   # (label, value) pairs shown when known


def title_tex(centre, edge, text, accent):
    def pair(k, v, f):                      # "label — value", or just the value (composer)
        return f(v) if k is None else f"{f(k)} — {f(v)}"
    cap = lambda x: iast(x).capitalize()
    composer = [v for k, v in TITLE_META if k is None]
    rows = r"\\[1.1em]".join(rf"{{\deva\fontsize{{24}}{{30}}\selectfont {pair(k, v, str)}}}\\[0.1em]"
                              rf"{{\iast\itshape\fontsize{{15}}{{19}}\selectfont {pair(k, v, cap)}}}"
                              for k, v in TITLE_META if k is not None)
    comp = "" if not composer else rf"""
  \node[anchor=south,yshift=1.6in,text=txt,align=center,opacity=0.9] at (current page.center)
       {{{{\deva\fontsize{{24}}{{30}}\selectfont {composer[0]}}}\\[0.1em]{{\iast\itshape\fontsize{{15}}{{19}}\selectfont {cap(composer[0])}}}}};"""
    rule = lambda y: (rf"""
  \draw[acc,line width=0.6pt] ([xshift=-2.2in,yshift={y}in]current page.center) -- ++(4.4in,0);
  \fill[acc] ([yshift={y}in]current page.center) circle (2.2pt);""")
    return tex(centre, edge, text, accent).split(r"\begin{tikzpicture}")[0] + rf"""\begin{{tikzpicture}}[remember picture,overlay]
  \shade[inner color=bgc,outer color=bge] ([xshift=-2in,yshift=-5in]current page.south west)
        rectangle ([xshift=2in,yshift=3in]current page.north east);
  \node[anchor=north,yshift=-0.7in,text=acc] at (current page.north)
       {{\deva\fontsize{{22}}{{26}}\selectfont ॥श्रीः॥}};{comp}{rule(1.35)}
  \node[anchor=center,yshift=0.3in,text=txt,font=\deva\fontsize{{80}}{{96}}\selectfont] at (current page.center) {{{TITLE_DEVA}}};
  \node[anchor=center,yshift=-0.75in,text=acc,font=\iast\itshape\fontsize{{34}}{{40}}\selectfont] at (current page.center) {{{TITLE_IAST}}};{rule(-1.3)}
  \node[anchor=north,yshift=-1.55in,text=txt,align=center,opacity=0.9] at (current page.center) {{{rows}}};
  \draw[acc,line width=0.4pt,opacity=0.5] ([xshift=0.8in,yshift=0.62in]current page.south west)
        -- ([xshift=-0.8in,yshift=0.62in]current page.south east);
  \node[anchor=south west,xshift=0.8in,yshift=0.3in,text=txt,opacity=0.62] at (current page.south west)
       {{\iast\fontsize{{11}}{{13}}\selectfont stotrasamhita.github.io \ \textbullet\ \ github.com/stotrasamhita/stotra-sangrahah}};
  \node[anchor=south east,xshift=-0.8in,yshift=0.3in,text=txt,opacity=0.62] at (current page.south east)
       {{\iast\fontsize{{11}}{{13}}\selectfont Chant generated by AI with Vāgdhenu \ \textbullet\ \ github.com/prathoshap/vagdhenu}};
\end{{tikzpicture}}
\end{{document}}
"""


def build(name, source):
    src = os.path.join(OUT, name + ".tex")
    open(src, "w", encoding="utf-8").write(source)
    subprocess.run([TECTONIC, "--chatter", "minimal", "--outdir", OUT, src], check=True)
    pdf = os.path.join(OUT, name + ".pdf")
    subprocess.run(["pdftoppm", "-png", "-r", "240", "-singlefile", pdf, os.path.join(OUT, name + "_2x")], check=True)
    subprocess.run([FFMPEG, "-loglevel", "error", "-y", "-i", os.path.join(OUT, name + "_2x.png"),
                    "-vf", "scale=1920:1080:flags=lanczos", os.path.join(OUT, name + ".png")], check=True)
    os.remove(os.path.join(OUT, name + "_2x.png"))
    print(os.path.join(OUT, name + ".png"))


def main():
    os.makedirs(OUT, exist_ok=True)
    if "--title" in __import__("sys").argv:
        for name in ("aubergine",):
            build("title_" + name, title_tex(*VARIANTS[name]))
        return
    for name, cols in VARIANTS.items():
        src = os.path.join(OUT, name + ".tex")
        open(src, "w", encoding="utf-8").write(tex(*cols))
        subprocess.run([TECTONIC, "--chatter", "minimal", "--outdir", OUT, src], check=True)
        pdf = os.path.join(OUT, name + ".pdf")
        subprocess.run(["pdftoppm", "-png", "-r", "240", "-singlefile", pdf, os.path.join(OUT, name + "_2x")], check=True)
        subprocess.run([FFMPEG, "-loglevel", "error", "-y", "-i", os.path.join(OUT, name + "_2x.png"),
                        "-vf", "scale=1920:1080:flags=lanczos", os.path.join(OUT, name + ".png")], check=True)
        os.remove(os.path.join(OUT, name + "_2x.png"))
        print(os.path.join(OUT, name + ".png"))


if __name__ == "__main__":
    main()
